# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cart', models.CharField(max_length=8, unique=True)),
                ('items', models.ManyToManyField(to='ykea.N_items')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='n_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item'),
        ),
    ]
