# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0002_auto_20180509_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='id_cart',
            new_name='idCarrito',
        ),
    ]
