# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='saldo',
            field=models.FloatField(default=1000),
        ),
    ]
