# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0005_auto_20180522_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='pastaCarrito',
            field=models.FloatField(default=0),
        ),
    ]
